- css/template.css
- index.html
- src/bridge/controllers/UserController.js
- Changed admin and user layout
- Full screen svg
- User 'logout' 
- Lots of other little things in preparation for the demo tomorrow
Check it out!
> Full screen svg with overlay, closes #14

- package.json
- src/bridge/bridge.module.js
- src/bridge/directives/bodies.js
- src/bridge/services/simulation.js
- src/bridge/services/simulator.js
Problem
=======
There is not integration between the mission control back end service and the bridge application.
Solution
========
Add angular resource as a dependency which allows abstracting binding to the Mission Control RESTful API. The initial implementation queries the latest simulation and resets the simulator with the result.
Howto Test
==========
> Create Mission Control Service; Closes #18

- src/bridge/directives/bodies.js
* made axis group
* position body group ahead of axis group
> [minor] Grid positioned behind bodies, closes #33

- index.html
Problem
=======
There is no mechanism to capture information about users of the demo.
Solution
========
Add Google Analytics to the applicaiton.
Howto Test
==========
> Add Google Analytics; Closes #42

- css/template.css
- index.html
- src/bridge/controllers/UserController.js
* updated user controller to accept data (backend integration
still required)
* uses bootstrap modal elements in keeping with the single page functionality
* tool bars are *more* responsive but still require a minimum 650px height
> Added views for sign in and registration, closes #38

- src/bridge/directives/bodies.js
Adds the calculation for the stars color and the radius of the habitable zone.  I wasn't exactly sure where to put these things so if they don't seem to be in the correct place feel free to move them.
> Star color and habitable zone

- css/template.css
- index.html
- src/bridge/controllers/BodyController.js
- src/bridge/directives/bodies.js
- src/bridge/directives/bodyData.js
What's new:
* Event listener on each body
* Body data directive displays and formats body attributes
* Directive is shown when a body is selected, and hidden when deselected
What's missing:
What to test:
* Open it up and see if the behavior matches your expectations
> Display information on body selection

- package.json
Problem
=======
Bridge currently does not use the latest and greatest of engine.
Solution
========
Update the dependencies!
How-to Test
===========
> Update Engine Dependency; Closes #57

- index.html
body data directive is not receiving data
Restore the original scope so that both the bodies directive and body data are contained within the bodyController scope.
> Hotfix: body scope issue

- index.html
Problem
=======
The DOM is getting mangled with multiple navs. This is becuase there are
redundant elements within the index file. This may of been becuase of a bad
merge conflict.
Solution
========
Renest the DOM elements and remove redundant tags.
Howto Test
==========
/cc @mkinsey
> Renest HTML; Closes #62

- src/bridge/directives/bodies.js
There is now more color variation for bodies with no luminosity
> Color variance for non-stars

- src/bridge/directives/bodies.js
Problem
=======
Removing elements from the DOM and appending new ones once per animation frame
is suffering performance from performance issues.
Solution
========
Use the D3 lifecycle to update existing dom elements.
Howto Test
==========
> Use D3 Data lifecycle for Optimal DOM Manipulation; Closes #52

- css/template.css
- index.html
- src/bridge/controllers/BodyController.js
- src/bridge/directives/bodyData.js
- src/bridge/filters/UnitFilter.js
No units are available for body data (#69) 
Angular's filter component should be used to dynamically display units, independent of simulation logic. A Settings modal should be added to manage User Selection
Select a body, open settings modal, change units, observe changes in directive.
> Unit Conversion

- src/bridge/directives/bodies.js
> Increased maximum zoom amount; Closes #85

- src/bridge/bridge.module.js
- src/bridge/controllers/UserController.js
- src/bridge/directives/bodies.js
- src/bridge/directives/br-fps-counter.js
- src/bridge/services/eventPump.js
Problem
-------
The simulation should begin paused.
Solution
--------
Currently the eventPump is resumed upon application standup which allows
animations to begin immediately. Removing this resume call starts the
application in a paused state.
Howto Test
----------
/cc @mkinsey
> Start Simulation Paused; Closes #90

- index.html
- src/bridge/controllers/UserController.js
- src/bridge/services/user.js
Problem
-------
Bridge has UI components for user registration and login but these do not function.
Solution
--------
Implement service to handle user registration and login functionality and wire it up to the UI components.
Howto Test
----------
References
----------
- @mkinsey This will require a bit of UI reworking to handle failures in
registration/login. The modal should only close on good events.
- Resolves #81
- Closes #82 
- Resolves #102 
- Sorry to step on your toes @dill-wood :goberserk:
> Add User Registration and Authentication

- gulpfile.js
- index.html
- package.json
- partials/simulation-list.html
- partials/simulation.html
- src/bridge/bridge.module.js
- src/bridge/controllers/SimulationController.js
Problem
-------
There is no way to segregate the application in to confined states of isolated functionality. This makes it difficult to list simulations or show a specific simulation.
Solution
--------
Add `angular-router` as a dependency and add the corresponding routes:
- `/s/` Lists all simulations
- `/s/:id` Loads the simulation with the given ID
- `/u/` List all simulations for a given user
- `/u/:id` Loads the simulation with the given ID
Howto Test
----------
- Open Bridge
- Notice that the defaul route is set to `#/s/random`
- Notice if you change the route to `#/s/` it lists a fake list of simulations
- Notice if you change the route to `#/u/benjic` you will see a list of fake
simulations.
- Notice if you change the route to `#/u/benjic/random`  you will get a random
simulation. …
> Add URL Router

- partials/simulation.html
- src/bridge/controllers/UserController.js
This simplifies UI by reducing redundant buttons.
* click play / pause button
* confirm that the icon changes, and the simulation toggles state
-  Closes #54
> Toggle play / pause with one button

- index.html
- partials/simulation.html
- src/bridge/bridge.module.js
- src/bridge/controllers/NavController.js
- src/bridge/controllers/UserController.js
- src/bridge/controllers/modals/registerModalController.js
- src/bridge/controllers/modals/signInModalController.js
- src/bridge/services/user.js
Problem
-------
Failures when dealing with registration and logins were unreported to the user and resulted in poor user experience. A user had no idea of what was happening in the background and did not know about failures when bad information was submitted and the back end server returned a failed response.
Solution
--------
Implement a minor state machine within the registration and sign in modals that directs the user as the registration and login processes are completed with the back end server. The modal indicates state changes to the user and dismisses on success. A user has an opportunity to resubmit information if bad data was supplied.
Howto Test
----------
References
----------
- @mkinsey Can you confirm this works correctly.
- @dill-wood This is an example of how logical error …
> Added Solid UX Around Logins

- package.json
- src/bridge/directives/simulation/bodies.js
You can test by running normally and ensuring colors are mostly random looking.
> Bridge now uses engine's colors; Closes #123; Closes #86

- src/bridge/directives/simulation/simulation.js
> Uniform horizontal/vertical scaling; Closes #131

- src/bridge/directives/simulation/ruler.js
ruler should now display appropriately & respond to zoom and pan.
> Fixed ruler translation issue, closes #132

- package.json
- src/bridge/directives/simulation/bodies.js
**Known issue:** When paused and not logged in, selected bodies keep a grey
ring around them even after another body is selected. I believe the
eventPump needs to be triggered for a frame to update the rendering.
This is fixed by PR #149 
* Closes #148
> White ring marks selected body

- css/template.css
- index.html
- partials/simulation-list.html
- src/bridge/controllers/AdminController.js
- src/bridge/controllers/modals/saveSimulationModalController.js
Problem
-------
When saving a simulation the user cannot give it meta information including a
title and description. This makes it impossible to differentiate different
simulations in a list.
Solution
--------
Provide the user with a modal to input data about the simulation before saving.
Howto Test
----------
- Attempt to save a simulation
References
----------
- Closes #152
- @mkinsey This addresses one of the points in our list
> Add Simulation Meta Information

- css/template.css
- index.html
- partials/simulation-list.html
- partials/simulation.html
- src/bridge/controllers/UserController.js
- src/bridge/controllers/simulationListController.js
- src/bridge/directives/simulation/bodies.js
Problem
-------
The lists of simulations are poorly laid out. In addition, failures to load
simulation lists are not handled.
Solution
--------
Update the application layout and styling to make simulation lists more pleasing
to the eye and handle loading events effectively.
Howto Test
----------
- Click on the simulation list button
- Notice now you can view `My Simulations`
- Selecting each of these options shows the correct list of simulations
- Each simulation list is rendered in a panel for niceness
- Calls to the backend to get lists are communicated to the user through alerts
properly.
References
- Closes #162
> Solidify User Simulation List UX

- css/template.css
- index.html
- partials/body-data.html
- src/bridge/controllers/BodyController.js
- src/bridge/directives/simulation/bodies.js
- src/bridge/directives/simulation/body-data.js
Problem
-------
The body data panel was left in a haphazhard state.
Solution
--------
Clean it up!
References
----------
- Closes #161
- @mkinsey Will you comb through this to see if there is anything nasty going
on.
> Update Edit Body UX

- src/bridge/directives/simulation/bodies.js
Prevents accidental dragging by setting a delay between the start of a drag and when that drag becomes effective in actually moving the body.
**How to test:**
-  Try quickly dragging and releasing bodies, notice it does not move the body
-  Try quickly dragging the body and holding, the body will teleport to the mouse after a moment
____
* Closes #139
> Drag threshold

- package.json
- partials/body-data.html
- src/bridge/controllers/BodyController.js
- src/bridge/directives/simulation/bodies.js
How to test:
* Select a body
* Try and type invalid input into all of the text boxes. *'e' is the only letter allowed*
* Play and pause intermittently while doing this
_______
* Closes #166
* Closes #164
> Protect against invalid input

- src/bridge/directives/simulation/bodies.js
To test:
* Try editing body position and velocity at various states.
* Ensure position and velocity are live updating
* Ensure invalid inputs do not break simulation and are cleared when simulation begins running
_____
* Closes #172
> Body data is live updating again

- partials/simulation.html
- src/bridge/controllers/UserController.js
To test:
* Add notes and bodies
* Press 'new' button
* Ensure bodies and notes have been destroyed
___
* Closes #174
> Added button for creating new simulation

- partials/note-data.html
- partials/simulation.html
- src/bridge/controllers/NoteController.js
Problem
-------
The noteController was added above the form elements which does not encapsulate
the note data panel heading. The close button included in this heading was not
able to reference the note controller preventing it from closing the panel on
click.
Solution
--------
Restructure the panel data body to so the controller encompasses the whole panel
structure.
Howto Test
----------
clicking the close icon.
References
----------
- Closes #177
- @aaroncameron21 Please review for correctness.
> Nest NoteController Correctly

- partials/note.html
- partials/simulation.html
- src/bridge/controllers/NoteController.js
- src/bridge/directives/simulation/note-data.js
Problem
-------
Angular does not know when the collection of visible notes changes.
Solution
--------
Watch the collection on the event loop and call $apply when the list changes.
Howto Test
----------
References
----------
> Update Angular with Updated Notes

- src/bridge/directives/simulation/ruler.js
I'm not actually sure what units they are in, whatever the Scale is in.  I tested it mathematically by manually calculating the distance between two notes using their positions and the ruler value seems to be approximately equal to the calculated value.
> Scale the ruler to use simulation units

- src/bridge/directives/simulation/bodies.js
How to test:
____
* Closes #187
> Drag notes

- src/bridge/controllers/AdminController.js
- src/bridge/directives/simulation/bodies.js
How to test:
____
* Closes #189
> Highlight selected note

- partials/body-data.html
- src/bridge/controllers/BodyController.js
- src/bridge/directives/simulation/habitable-zones.js
Adds functionality to toggle habitable zones, via the body data directive.
**How to test**
Closes #142
> Toggle habitable zones

- index.html
- package.json
- partials/simulation.html
- src/bridge/controllers/UserController.js
- src/bridge/directives/simulation/bodies.js
Hover over / press buttons and witness the tooltips
____
* Closes #91
> Tooltips on buttons

- src/bridge/directives/simulation/paths.js
Path colors now match the body's color. This also removes the path hover animation, as it was computationally expensive.
____
* Closes #205 
* Closes #206
> Path colors match body colors

- css/template.css
- src/bridge/directives/simulation/habitable-zones.js
The application should look nice in low-contrast environments (such as on projectors). Habitable zones should also have more contrast for color blind users.
**Test**
Try out the application, preferably in an area with high ambient light. I am certainly open to feedback/suggestions!
> Increase color contrast

- src/bridge/directives/simulation/ruler.js
Problem
-------
The Ruler does not show numerical values in terms of the selected units.
Solution
--------
Use the Units service to label the tick accordingly.
Howto Test
----------
References
----------
- Closes #218
- Please note this does not update an existing ruler.
> Add Units Filtering to Ruler

- package.json
> Prepare 0.1.0 Release

- partials/body-data.html
- partials/note-data.html
- src/bridge/bridge.module.js
- src/bridge/controllers/AdminController.js
- src/bridge/controllers/BodyController.js
- src/bridge/directives/simulation/bodies.js
added tooltips on data panels
removed non-functioning buttons
> UI Cleanup

- css/template.css
- package.json
- partials/body-data.html
- partials/note-data.html
- partials/simulation.html
- src/bridge/bridge.module.js
- src/bridge/controllers/AdminController.js
- src/bridge/controllers/BodyController.js
- src/bridge/controllers/NoteController.js
- src/bridge/controllers/UserController.js
- src/bridge/directives/simulation/axis.js
- src/bridge/directives/simulation/bodies.js
- src/bridge/directives/simulation/paths.js
- src/bridge/directives/simulation/ruler.js
- src/bridge/directives/simulation/simulation.js
- src/bridge/directives/simulation/vectors.js
* Slight path refactoring
* Limits number of paths
* Closes gap between path and body
* Deletes last point in path when max is reached instead of deleting whole path (Shifting arrays is surprisingly efficient)
> Refactor paths / Limit paths

- css/template.css
- package.json
- partials/simulation.html
- src/bridge/controllers/trackerController.js
* Visual enhancements
* Tracker now calculates/displays semi-major axis, semi-minor axis and eccentricity
* Tracker now updates data on every completed orbit
> Tracker enhancement

- index.html
- partials/body-data.html
- src/bridge/directives/simulation/ruler.js
- src/bridge/services/units.js
Addresses a few minor touches for the presentation tomorrow
- Filter ruler input
- Change default units for distance (au) and time (yr)
- Remove unit conversion from radius, leave as default (meters)
**Testing**
**References**
closes #234, #235 , #236
> Issue#234/default units
