gulpfile.js
This simplifies the gulp file and includes a watcher task to rebuild source on changes. If a file changes in the src directory it will rebuild.
/cc @mkinsey
=> Add source watcher for JS; Closes #6

gulpfile.js, index.html, package.json, src/bridge/bridge.module.js, src/bridge/controllers/AdminController.js, src/bridge/controllers/UserController.js, src/bridge/directives/br-fps-counter.js, src/bridge/directives/testsvg.js, src/bridge/services/eventPump.js, src/bridge/services/simulation.js
Problem
=======
The engine needs to be imported into bridge and wired up to the event pump.
Solution
========
Do it.
Howto Test
==========
- Update Dependencies
- `npm install && bower install`
- Build Source
- `gulp`
- This includes a new step which uses *browserify* to allow the use of
CommonJS modules within client side code.
- Examine Application in Window
- Press the Play button to start the eventPump
- Observe the console and a periodic call to printState will dump the
simulation state as it is driven by the event pump.
=> Integrate Engine and Bridge Repositories; Closes #16

gulpfile.js, src/bridge/directives/br-fps-counter.js, src/bridge/directives/simulator_pump.js, src/bridge/services/eventPump.js
The bridge will now work with current versions of the engine. I added a path to the engine/src/*.js files to the bridge's gulpfile. Now, the fps counter directive also pumps the simulator and prints the state to the console in one second intervals. The engine folder should be placed next to the bridge folder, and everything should work from that point. I'll update the readme in the engine repo to match.
=> Integration of bridge and engine

package.json
Problem
=======
We are tracking master of Engine as a dep. This may introduce oops as features
are expanded.
Solution
========
Use the recent release as the pinned version.
Howto Test
==========
=> Pin Engine Version; Closes #27

Dockerfile, gulpfile.js, package.json
Problem
=======
There no means to automatically build the project for deployment.
Solution
========
Add configuration so that an automated docker build can occur whenever there is
push to a branch or PR. This allows the demo service to reload any new additions
to the project more frequently.
This containerization stuff is kind of ancillary. You don't have to worry so
much about it. Just know it is there.
Howto Test
==========
[docker]: https://hub.docker.com/r/orbitable/bridge/builds/
=> Dockerize Bride for Deployment; Closes #30

src/bridge/services/simulation.js
Problem
=======
When resources are requested in a mixed protocol environment the it introduces
errors in firefox. For example when serving via https and a request is made to
an http simluations api endpoint the request is rejected.
Solution
========
Use relative protocol addresses to that API calls use the same underlying
protocols.
Howto Test
==========
- Open developer tools
- Navigate to resources/network to see list of recent network requests
- Search for the /simuations/random api call and confirm it used http as the
protocol.
=> Add relative protocol URI for simulations API Call; Closes #45

package.json, src/bridge/directives/bodies.js, src/bridge/services/simulator.js
Units are now scaled down for d3 rendering and a much larger tilmestep
is passed to the simulator. Prep for version 0.0.1.
=> Down-scaling units from simulator

src/bridge/directives/bodies.js
Added a value to d.radius to ensure it would be > 1 when divided by the sim scale.
=> Quickfix for negative radius values

package.json, src/bridge/directives/bodies.js
Problem
=======
The habitable zones are rendering on top of bodies preventing mouse clicks from
registering on the body.
Solution
========
Move habitable zones to a seperate group.
Howto Test
==========
=> Render Habitable Zones in Seperate Group; Closes #59

src/bridge/controllers/UserController.js
Problem
=======
The only way to refresh the simuation is to reload the page. A refresh button is
defined but has no functionality.
Solution
========
Use the controller.refresh function to query mission control for a new
simulaiton and load it into the simulator.
Howto Test
==========
=> Hookup Simulation Refresh; Closes #64

src/bridge/directives/bodies.js
Problem
=======
We missed the rename of the colorScale function.
Solution
========
Use the correct name.
Howto Test
==========
=> Use Correct Color Selection Function; Closes #75

src/bridge/controllers/UserController.js
Problem
-------
The path data should reset when a simulation resets. Existing paths will reamin after a simulation reset.
Solution
--------
Clear the global variables that store the path data.
*This is a band aid to a bigger problem.* #93 has been created to figure out a better way of storing annotation data in composition with simulaton data.
Howto Test
----------
- /cc @alexander-dunn
=> Reset Line Data on Reset; Closes #89

package.json, src/bridge/bridge.module.js, src/bridge/controllers/UserController.js, src/bridge/services/user.js
Problem
-------
User state and Session is stored in memory and lost on a page load. This means a
user would have to re login with every page reload.
Solution
--------
Store the session and user information in a cookie which persists across page
loads.
Howto Test
----------
- Run `npm install` angular-cookies was added as a dep.
- Run `gulp`
- Notice you are not logged in
- Create account if you don't have one
- It should log you in immediately refresh the page to confirm you remain logged
in.
- Log out. Refresh the page to confirm you remain logged out.
- Log back in with supplied credentials. 
- Refresh the page and confirm you remain logged in as your user.
References
----------
- This closes #107
=> Persist User and Session State

partials/simulation-directive.html, src/bridge/directives/simulation/axis.js, src/bridge/directives/simulation/bodies.js, src/bridge/directives/simulation/habitable-zones.js, src/bridge/directives/simulation/paths.js, src/bridge/directives/simulation/ruler.js, src/bridge/directives/simulation/simulation.js, src/bridge/directives/simulation/vectors.js
Problem
-------
Scaling has been done with constant values. This has made positioning objects on the coordinate plane difficult.
Solution
--------
Use static bounds to define a scaler function that will provide a window relative position for a given x or y value in the simulation coordinate space.  This scaler can also invert values by taking a window x or y value and convert it to the coordinate plane.
Howto Test
----------
References
----------
- @mkinsey This provides a `scope.xScale` and `scope.yScale` that can be used to scale values. Each of these scales has an `invert(n)` function that will translate a svg position into a simulation coordinate position.
- Closes #56
- This relates to the issues in #112 and #96
=> Provide a Universal Scaler

.travis.yml, gulpfile.js, package.json
Problem
-------
We have no way of running automated tests for the repo.
Solution
--------
Add a test task in the task runner and add configuration to have Travis CI run this task.
Howto Test
----------
- ![1460646116](https://cloud.githubusercontent.com/assets/135916/14532831/b01f3330-021f-11e6-83c7-776f27d09d9b.png)
References
----------
- @mkinsey I will follow up with setup test runners for Angular and Integration tests.
- Closes #127
[ci_#3]: https://travis-ci.org/orbitable/bridge/builds/123078602
=> Add Travis CI Support

partials/simulation-list.html, partials/simulation.html, src/bridge/bridge.module.js, src/bridge/controllers/AdminController.js, src/bridge/controllers/simulationListController.js, src/bridge/services/simulation.js
Problem
-------
It is not possible to load or save a simulation to mission control form the bridge interface.
Solution
--------
Tie the Simulation and UserSimulation resource services to the UI to to get basic functionality. This allow the admin panel to save a current simulation state as well as updates the app router to load a simulation state for a given ID.
Howto Test
----------
- Visit [http://localhost:8000/#/s/random](http://localhost:8000/#/s/random)
saved simulation.
- Visit [http://localhost:8000/#/s/](http://localhost:8000/#/s/)
- Visit [http://localhost:8000/#/u/benjic](http://localhost:8000/#/u/benjic)
- Visit the above link but change it to your user name
References
----------
- Closes #137
- ~~This is dependent on orbitable/mission-control#57 being deployed to confirm
user …
=> Add Saving/Loading Simulation From Mission Control

partials/body-data.html, src/bridge/controllers/BodyController.js, src/bridge/directives/simulation/bodies.js, src/bridge/directives/simulation/click-to-edit.js
The ability to mutate a simulation should be limited to an authorized user
Make auth checks when
* dragging
* updating
* deleting
While logged in
While logged out
Closes #140
=> Limit mutation functions

.jscsrc, src/bridge/directives/simulation/bodies.js
Problem
-------
A drag event entered on the habitable zone causes the center body to be
reposition with the drag. This is incorrect as the habitable zone is a function
of a body's luminosity and position. It should move with the body exclusively.
Solution
--------
The call on the d3 selection of all circles cause the body drag handle to be
bound to the habitable zone, `d3.selectAll('circle').call(drag);`. This is the
cause of the issue. The body positioning drag events should be bound to the
body as exemplified below.
**Bonus** I restructured the code to follow the Google JS coding styles as
recommended by JSCS. Enable the JSCS linter in your editor to get hints for a
concise code style.
Howto Test
----------
Reference
---------
- Closes #143
- @orbitable/all
=> Correct Dragging of Habitable Zones

.jscsrc, src/bridge/directives/simulation/bodies.js, src/bridge/directives/simulation/vectors.js
Problem
-------
The vector arrows render based of a transient data structure which causes them to redraw multiple times. The vector arrow is a function of a given body and should only draw once in accordance with the properties of that body.
Solution
--------
Refactor how vector arrows are drawn to use the simulation body as the d3 data source. This ensures the arrows are drawn once per body.
Howto Test
----------
References
----------
- Closes #125
- @aaroncameron21 @alexander-dunn Please let me know if I missed any
functionality.
=> Refactor Vector Rendering

package.json, src/bridge/controllers/AdminController.js, src/bridge/controllers/BodyController.js, src/bridge/controllers/SimulationController.js, src/bridge/controllers/UserController.js, src/bridge/directives/simulation/bodies.js, src/bridge/services/eventPump.js
Calling eventPump.step(false,true) will update rendering without affecting simulation. This prevents unwanted simulation updating when user modifies the simulation, it also removes the issue where the simulation always starts one frame in.
TODO:
* Closes #149;
=> Event pump can update without affecting simulation

src/bridge/controllers/SimulationController.js
Problem
-------
The title of the page does not reflect the currently loaded simulation.
Solution
--------
Update document title when loading a simulation.
Howto Test
----------
References
----------
- Closes #154 
- @mkinsey This is a nice to have.
=> Update Page Title with Simulation Title

src/bridge/directives/simulation/bodies.js
Problem
-------
The isSelected function will fail if selectedBody on the scope is not set. This is introducing issues when initially loading a simulation.
Solution
--------
Add a guard to test if `selectedBody` is set.
References
----------
- Closes #157
=> Add Guard to isSelected Function

partials/body-data.html, src/bridge/controllers/BodyController.js
Sets the text input boxes for body modification to 'readonly' while the simulation is running. This prevents the user from making changes to body attributes unless the simulation is paused.
How to test:
* Select a body, see that you can modify its attributes
* Press play, you can no longer modify attributes
* Press pause, you can modify attributes again.
_____
* Closes #170
=> Disables body input boxes while running

partials/simulation.html, src/bridge/controllers/UserController.js, src/bridge/directives/br-fps-counter.js
Problem
-------
When a user clicks reset within bridge a random simulation is generated. The
correct behavior is to reset the currently selected simulation to it's initial
state.
Solution
--------
Check the route parameters for a simulation ID and reload the simulation with
the given ID. If none is present, load the random simulation.
Howto Test
----------
- Go to the simulation [list](http://localhost:8001/#/s/)
- Choose a simulation
- Ensure the simulation plays
- Reset the simultion and confirms it resets back to the beginning state
References
----------
- **Bonus** Cleaned up play button behaviour to be a little more DRY
- Closes #159
- Inspired an update to [engine](https://github.com/orbitable/engine/pull/73)
which resets the simulation time as well.
=> Add Correct Reset Behaviour

partials/note-data.html, src/bridge/controllers/NoteController.js, src/bridge/directives/simulation/bodies.js
Problem
-------
When selecting a note the selected body scope object is used to hold it's
reference but this causes issues when dealing with interacting with the selected
body as if it is a body.
Solution
--------
Add an independent scope field labeled `selectedNote` which holds the handle to
the last selected note so there is no conflict between the two.
Howto Test
----------
References
----------
- Closes #179
=> Use selectedNote Scope Field for Note Selection

src/bridge/directives/simulation/bodies.js
Problem
-------
When updating the scope object there is not explicit call to $apply which
prevents angular from diffing the scope update.
Solution
--------
Call apply when selecting a new body or note to signal to angular that the scope
has been updated. This causes any other reference to the scope to be
reevaluated.
Howto Test
----------
References
----------
- Closes #181
- @aaroncameron21 This corrects the selection issue.
=> Flag Scope as Dirty On Selection

css/template.css, partials/simulation-list.html, partials/simulation.html, src/bridge/controllers/BodyController.js, src/bridge/controllers/UserController.js, src/bridge/directives/simulation/bodies.js, src/bridge/directives/simulation/body-data.js, src/bridge/directives/simulation/ruler.js
Problem
-------
The panels have differing apperance and the UX realated to how they interact is
muddled.
Solution
--------
Use css classes to unify the look of all right and left sidebars as well as
define how panels may show up.
Howto Test
----------
panel.
References
----------
- Closes #183
- Closes #141 
- Closes #72 
- @aaroncameron21 Would you like to confirm the panels operate as you would
expect?
=> Unify Panel UX and Apperance

src/bridge/controllers/SimulationController.js, src/bridge/controllers/UserController.js, src/bridge/controllers/modals/saveSimulationModalController.js, src/bridge/services/note.js
Problem
-------
Notes are not saved alongside a simulation.
Solution
--------
Use the new notes endpoint available through mission control to save any notes alongside a simulation.
Howto Test
----------
**This is depdendent on a deploy of mission control after [https://github.com/orbitable/mission-control/pull/70](https://github.com/orbitable/mission-control/pull/70) is merged**.
accordingly.
expected.
References
----------
- Closes #192
- @aaroncameron21
=> Add Note Persistance

index.html, partials/body-data.html, partials/note-data.html, partials/simulation.html, src/bridge/controllers/BodyController.js, src/bridge/directives/br-fps-counter.js, src/bridge/directives/simulation/bodies.js, src/bridge/directives/units.js, src/bridge/services/units.js
Problem
-------
The user selectable units are non functional as the model for body data has been shifted.
Solution
--------
A unit directive allows a for element to parse and cast a raw model data value into a derived value based on a selected unit set in the Units service. This allows the form to show the value of the simulation in different units without haveing to convert within the simulator.
Howto Test
----------
References
----------
- Closes #176
- @mkinsey This adds bidirectional unit application to input fields.
=> Add Units Service and Directive

partials/simulation-directive.html, src/bridge/directives/simulation/bodies.js, src/bridge/directives/simulation/selector.js
Instead of using the bodies' 'stroke' attribute to indicate selected bodies, I've added a directive to do something similar. This prevents visual issues when using browsers that handle the stroke attribute differently.
To test:
___
* Closes #214
=> Adds selector directive

src/bridge/directives/simulation/simulation.js
Previously, there were issues with large-radius bodies where the visual representation of the body on screen was smaller than the space that the actual body occupied. This caused other bodies to 'collide' with it while appearing to be far away from it. 
This fix ensures that the visual representation of the body is no smaller than its collision bounds.
To test:
* Set the center body to larger radii
* Run the simulation and ensure that bodies are not destroyed until they at least make visual contact with the large body.
_____
* Closes #209
=> Quick fix to ensure visual radius is accurate

src/bridge/controllers/UserController.js
Problem
-------
When a new simulation is created the existing paths are not wiped causing the exisiting paths to be reattributed to the new bodies causing strange path issues.
Solution
--------
Write a single handler for simulation loading and use it in both new simualation as well as resets agains the end. This ensures the logic lives in one place and changes to one will affect all applicable instances.
Howto Test
----------
Reference
---------
- Closes #204
=> Unify Simulation Reset

src/bridge/directives/simulation/axis.js, src/bridge/directives/simulation/simulation.js
Problem
-------
Some objects which depend on scope value changes for positioning info are not
being redrawn when the canvas is panned or zoomed.
Solution
--------
The scope is never updated in these events causing angular to never re render
anything. By forcing an apply on top level pans and zooms all of the dependent
objects are updated.
Howto Test
----------
References
----------
- Closes #203
=> Update Scope with Zoom or Pan Event

partials/simulation.html
When a user is not logged in the admin group should not be visible and the save/new simulation buttons should be hidden.
=> Hide unavailable buttons when not logged in

src/bridge/controllers/UserController.js, src/bridge/directives/simulation/bodies.js, src/bridge/directives/simulation/paths.js, src/bridge/services/paths.js, src/bridge/services/simulator.js
Problem
-------
Path data can be left in strange states which leaves path artifacts on the
screen.
Solution
--------
Remove paths from the global namespace and add them as a service. In additon
interceptors around the simulation reset and resetLocal calls allow the path
data to be reset in cordination with these function calls. This ensures the path
data is reset any time the simulation bodies move outside of a update call.
Howto Test
----------
- Reset locally
- Reset from server
- Reset by selecting another simulation
References
----------
- Closes #237
=> Add Reset Interceptors for Path Resetting
